# Default values for environment variables intended for local development
# These values are supplied by the environment for cloud-deployed services
# Or for connecting to cloud deployed services

RPM_AWS_ACCESS_KEY: local-deploy
RPM_AWS_SECRET_ACCESS_KEY: local-deploy
RPM_JWT_SECRET: local-deploy
RPM_ZUUL_ACCESS_HEADER: local-deploy
RPM_ZUUL_ACCESS_SALT: local-deploy