# Default values for environment variables intended for local development
# These values are supplied by the environment for cloud-deployed services
# Or for connecting to cloud deployed services

CONFIG_SERVICE_URL: http://rpm-264761131.us-east-1.elb.amazonaws.com/config
