#use this yml file to run locally. Place in src/main/resources folder of auth-service.
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 10001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: http://localhost:10001
    statusPageUrl: http://localhost:10001/actuator/info
    healthCheckUrl: http://localhost:10001/actuator/health
    homePageUrl: http://localhost:10001
    instance-id: auth-service
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    secret: ${RPM_JWT_SECRET}
