server:
  port: 8080

# eureka:
#   client: 
#     serviceUrl: 
#       defaultZone: http://localhost:8761/eureka
#   instance: 
#     preferIpAddress: 

spring: 
  cloud: 
    gateway: 
      discovery: 
        locator: 
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
