server:
  port: 8080

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka

spring: 
  cloud: 
    gateway: 
      discovery: 
        locator: 
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

rpm: 
  gateway: 
    header: X-RPM-Gateway
    secret: local-deploy
    salt: local-deploy
