server:
  port: 8080

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  instance: 
    preferIpAddress: true

spring: 
  cloud: 
    gateway: 
      routes: 
      - id: auth-service
        url: lb://auth-service
        predicates:
          - Path=/api/test/**