server:
  port: 8080

eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  instance: 
    preferIpAddress: true

spring: 
  cloud: 
    gateway: 
      discovery: 
        locator: 
          enabled: true
          lower-case-service: true
      routes: 
      - id: test
        url: lb://AUTH-SERVICE
        predicates:
          - Path=/test/**