spring:  
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

server:
  port: 10002
  tomcat:
    max-http-post-size: 2MB
    max-swallow-size: 2MB 

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
     
management:
  endpoints:
    web:
      exposure:
        include: '*'

aws:
  config:
    aws-access-key-id: ${RPM_AWS_ACCESS_KEY}
    aws-secret-access-key: ${RPM_AWS_SECRET_ACCESS_KEY}
    s3-endpoint: https://s3.eu-west-2.amazonaws.com
    bucket-name: rpm-project-assets
    bucket-region: eu-west-2