#Use this yml file to run zuul locally. Place in src/main/resources folder of zuul-service.
server:
  port: 8080
  tomcat:
    max-http-post-size: 2MB
    max-swallow-size: 2MB
  
spring:  
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

ribbon:
  ReadTimeout: 9999999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

zuul:
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:10001
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Cookie,Set-Cookie
    project-service:
      path: /project/**
      url: http://localhost:10002
      service-id: project-service
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
security:
  jwt:
    secret: ${RPM_JWT_SECRET}
