spring:
  application: zuul-service

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  ignored-services: *
  routes:
  - auth-service:
      path: /auth/**
      service-id: rpm-auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
  - project-service:
      path: /projects/**
      service-id: rpm-project-service