server:
  port: 8762
  tomcat:
    max-http-post-size: 2MB
    max-swallow-size: 2MB
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  use-forward-headers: true
  
spring:  
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true

ribbon:
  ReadTimeout: 9999999

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://rpm-elb-996808586.us-east-1.elb.amazonaws.com/rpm-eureka/eureka
    register-with-eureka: false
    fetch-registry: false
#   instance:
#     hostname: http://rpm-elb-996808586.us-east-1.elb.amazonaws.com/rpm-zuul
#     statusPageUrl: http://rpm-elb-996808586.us-east-1.elb.amazonaws.com/rpm-zuul/actuator/info
#     healthCheckUrl: http://rpm-elb-996808586.us-east-1.elb.amazonaws.com/rpm-zuul/actuator/health
#     homePageUrl: http://rpm-elb-996808586.us-east-1.elb.amazonaws.com/rpm-zuul
#     instance-id: zuul-service

zuul:
  ignoreSecurityHeaders: false
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      url: http://rpm-alb-1871573764.eu-west-2.elb.amazonaws.com/auth
      service-id: auth-service
      strip-prefix: true
      sensitive-headers: Cookie,Set-Cookie
    project-service:
      path: /project/**
      sensitiveHeaders:
      url: http://rpm-alb-1871573764.eu-west-2.elb.amazonaws.com/project
      strip-prefix: true
      service-id: project-service
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        

